In [2]:
#question 1
#a
import numpy as np
arr=np.array([1,2,3,6,4,5])
arr=np.flip(arr)
print("Reversed array is : ")
arr

Reversed array is : 


array([5, 4, 6, 3, 2, 1])

In [3]:
#b
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
arr=array1.flatten()
arr
array1 = np.array([[1,2,3],[2,4,5],[1,2,3]])
arr1=array1.reshape(1,9)
arr1


array([[1, 2, 3, 2, 4, 5, 1, 2, 3]])

In [15]:

#c
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
if np.array_equal(arr1,arr2):
  print("equal")
else:
  print("Not equal")


equal


In [ ]:
#d
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3,])
#for x
ans=np.bincount(x)
maximum=max(ans)
for i in range(len(ans)):
  if ans[i]==maximum:
   print(i)
#for y
ans=np.bincount(y)
maximum=max(ans)
for i in range(len(ans)):
  if ans[i]==maximum:
   print(i)

In [ ]:
#e
gfg = np.matrix('[4,1,9; 12,3,1; 4,5,6]')
print("Sum of all elements of array is ",np.sum(gfg))
print("Column wise sum of elements of array is ")
print(np.sum(gfg,axis=0))
print("Row wise sum of elements of array is ")
print(np.sum(gfg,axis=1))

In [ ]:
#f
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print("Sum of diagonals is ",np.trace(n_array))
eVal,eVec = np.linalg.eig(n_array)
print("Eigen values of given array are ")
print(eVal)
print("Eigen vector of given array is ")
print(eVec)
print("Inverse of given array is ")
print(np.linalg.inv(n_array))
print("Determinant of given array is ")
print(np.linalg.det(n_array))

In [20]:
#g
p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])
print("p * q is ")
print(np.matmul(p,q))
print("Covariance between these is ")
print(np.cov(p,q))
print()
p = np.array([[1,2],[2,3],[4,5]])
q = np.array([[4,5,1],[6,7,2]])
print("p * q is")
print(np.matmul(p,q))
q = q.reshape(3,2)
print("Covariance between these is")
print(np.cov(p,q))

p * q is 
[[16 19]
 [26 31]]
Covariance between these is 
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

p * q is
[[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance between these is
[[  0.5   0.5   0.5   0.5   2.5  -2.5]
 [  0.5   0.5   0.5   0.5   2.5  -2.5]
 [  0.5   0.5   0.5   0.5   2.5  -2.5]
 [  0.5   0.5   0.5   0.5   2.5  -2.5]
 [  2.5   2.5   2.5   2.5  12.5 -12.5]
 [ -2.5  -2.5  -2.5  -2.5 -12.5  12.5]]


In [ ]:
#h
x = np.array([[2,3,4],[3,2,9]])
y = np.array([[1,5,0],[5,10,3]])
print("Inner product is ")
print(np.inner(x,y))
print("Outer product is ")
print(np.outer(x,y))
print("Cartesian product is ")
print(np.cross(x,y))

In [ ]:
#question 2
#i
arr = np.array([[1,-2,3],[-3,4,-6]])
print("Element wise absolute values are ")
print(np.abs(arr))
#ii
print("Percentile of flattened array")
print("25th ",np.percentile(arr.flatten(),25))
print("50th ",np.percentile(arr.flatten(),50))
print("75th ",np.percentile(arr.flatten(),75))
print("Percentile for each column ")
print("25th ",np.percentile(arr,25,axis=0))
print("50th ",np.percentile(arr,50,axis=0))
print("75th ",np.percentile(arr,75,axis=0))
print("Percentile for each row")
print("25th ",np.percentile(arr,25,axis=1))
print("50th ",np.percentile(arr,50,axis=1))
print("75th ",np.percentile(arr,75,axis=1))
#iii
print("Mean of flattened array")
print(np.mean(arr.flatten()))
print("Row wise mean is ")
print(np.mean(arr,axis=1))
print("Column wise mean is ")
print(np.mean(arr,axis=0))

print("Median of flattened array")
print(np.median(arr.flatten()))
print("Row wise median is ")
print(np.median(arr,axis=1))
print("Column wise median is ")
print(np.median(arr,axis=0))

print("Standard deviation of flattened array")
print(np.std(arr.flatten()))
print("Row wise standard deviation is ")
print(np.std(arr,axis=1))
print("Column wise standard deviation is ")
print(np.std(arr,axis=0))

#b
a = np.array([-1.8,-1.6,-0.5,0.5,1.6,1.8,3.0])
print("Floor values ",np.floor(a))
print("Ceil values ",np.ceil(a))
print("Truncated values ",np.trunc(a))
print("Rounded values ",np.round(a))

In [3]:
#question 3
#a
arr = np.array([10,52,62,16,16,54,453])
print("Sorted array is ",np.sort(arr))
print("Indices of sorted array ",np.argsort(arr))
print("4 smallest elements  ",np.sort(arr)[0:4])
print("5 largest elements ",np.sort(arr)[len(arr)-1:len(arr)-6:-1])

#b
arr = np.array([1.0,1.2,2.2,2.0,3.0,2.0])
print("Integer values are ",arr[arr==arr.astype(int)])
print("Float values are ",arr[arr!=arr.astype(int)])

Sorted array is  [ 10  16  16  52  54  62 453]
Indices of sorted array  [0 3 4 1 5 2 6]
4 smallest elements   [10 16 16 52]
5 largest elements  [453  62  54  52  16]
Integer values are  [1. 2. 3. 2.]
Float values are  [1.2 2.2]


In [4]:
#question 4
def img_to_array(path):
    f = open(path,'rb')
    newfile = open('newfile.txt', 'wb')

    for line in f:
        newfile.write(line)

img_to_array('/Users/gurpreetsingh/Downloads/pexels-denise-2759315.jpg')

